### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jonpugh** [operations-platform/site-server#4]
- [ ] Platform User SSH Access.
  - [ ] Copy all users's `authorized_keys` into `platform` user's `authorized_keys`.
- [ ] GitOps Config File Examples
  - [ ] GitHub 
  - [ ] BitBucket
  - [ ] GitLab
- [ ] Backup workflow.
